#!/usr/bin/env python3
# =============================================================================
#  T1 : main per-workload speed-quality table
#  Per (workload, method): speedup vs target_s50 (paired median time ratio),
#  GT-m, GT-b, LPIPS_t (median).  Reduced-step targets + strict/default presets.
#  USES lpips_t only for files whose ref is s50 (phase2/largemask/instmask);
#  nsrep files are excluded here.
#
#  Inputs: phase2_per_image.csv, largemask_per_image.csv, instmask_per_image.csv
#  Usage:  python make_t1_main.py --data /path/to/csvs
#  Output: table_t1_main.tex
# =============================================================================
import argparse, os, sys
import numpy as np, pandas as pd

FILES=["phase2_per_image.csv","largemask_per_image.csv","instmask_per_image.csv"]
# methods to show, in order (edit to match your run)
METHODS=["target_s50","target_s40","target_s30","target_s24","target_s20",
         "target_s16","target_s12","target_s8","freqspec_strict","freqspec_default"]

def load(d):
    fr=[]
    for f in FILES:
        p=os.path.join(d,f)
        if os.path.exists(p): fr.append(pd.read_csv(p))
    if not fr: sys.exit("no CSVs")
    return pd.concat(fr, ignore_index=True)

def main():
    ap=argparse.ArgumentParser(); ap.add_argument("--data",default="."); a=ap.parse_args()
    df=load(a.data)
    runs=sorted(df["run"].unique())
    with open("table_t1_main.tex","w") as f:
        f.write("% auto-generated by make_t1_main.py\n")
        f.write("\\begin{table*}[t]\\centering\\small\\setlength{\\tabcolsep}{4pt}\n")
        f.write("\\caption{Per-workload speed--quality (paired, manifest-fixed). "
                "Speedup vs.\\ s50; GT-m/GT-b to ground truth; LPIPS$_t$ vs.\\ s50 trajectory.}\n")
        f.write("\\label{tab:main}\n\\begin{tabular}{@{}ll"+ "cccc" +"@{}}\n\\toprule\n")
        f.write("Workload & Method & Speedup & GT-m & GT-b & LPIPS$_t$ \\\\\n\\midrule\n")
        for run in runs:
            d=df[df["run"]==run]
            t50=d[d["method"]=="target_s50"].set_index("idx")["time_sec"]
            first=True
            for m in METHODS:
                sub=d[d["method"]==m]
                if not len(sub): continue
                tm=sub.set_index("idx")["time_sec"]
                j=tm.index.intersection(t50.index)
                spd=(t50.loc[j]/tm.loc[j]).median() if len(j) else np.nan
                gm=sub["gt_masked_lpips"].median()
                gb=sub["gt_boundary_lpips"].median() if "gt_boundary_lpips" in sub else np.nan
                lt=sub["lpips_t"].median() if "lpips_t" in sub else np.nan
                wl=run if first else ""; first=False
                mm = m.replace("target_","").replace("freqspec_","FreqSpec-").replace("_","\\_")
                f.write(f"{wl} & {mm} & {spd:.2f}$\\times$ & {gm:.4f} & "
                        f"{gb:.4f} & {lt:.4f} \\\\\n")
            f.write("\\midrule\n")
        f.write("\\bottomrule\n\\end{tabular}\n\\end{table*}\n")
    print("wrote table_t1_main.tex over workloads:", runs)

if __name__=="__main__":
    main()
