#!/usr/bin/env python3
# =============================================================================
#  F3 : step-robustness boundary map
#  Paired per-image degradation  D_i(s) = GT-m_i(s) - GT-m_i(s24)  over the
#  hard workloads.  y = mean D(s) with bootstrap 95% CI; secondary P(D>0.02).
#  Highlights the s20 > s16 non-monotonicity on large masks.
#  USES gt_masked_lpips ONLY (never lpips_t) so nsrep CSVs (ref=s24) are safe.
#
#  Inputs: largemask_per_image.csv, instmask_per_image.csv (or objectremoval)
#  Hard workloads (edit HARD to match run names):
#     largemask_coco, largemask_ffhq, largemask_places2, objectremoval_coco
#  Columns: run, idx, method, gt_masked_lpips
#           method values include target_s24, target_s20, target_s16,
#           target_s12, target_s8
#
#  Outputs: fig_f3_boundary.pdf/.png, table_t_boundary.tex, table_t_nonmono.tex
#  Usage:  python make_f3_boundary.py --data /path/to/csvs
# =============================================================================
import argparse, os, sys
import numpy as np, pandas as pd
import matplotlib; matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib import font_manager

STEPS = [20, 16, 12, 8]          # relative to s24 baseline
BASE  = 24
NBOOT = 2000
SEED  = 0
HARD  = ["largemask_coco","largemask_ffhq","largemask_places2","objectremoval_coco"]
FILES = ["largemask_per_image.csv","instmask_per_image.csv","phase2_per_image.csv"]

def load(data_dir):
    fr=[]
    for f in FILES:
        p=os.path.join(data_dir,f)
        if os.path.exists(p): fr.append(pd.read_csv(p))
    if not fr: sys.exit("no CSVs found")
    df=pd.concat(fr, ignore_index=True)
    need={"run","idx","method","gt_masked_lpips"}
    if need-set(df.columns): sys.exit(f"missing cols: {need-set(df.columns)}")
    return df

def paired_delta(df, run, s):
    d=df[df["run"]==run]
    a=d[d["method"]==f"target_s{s}"].set_index("idx")["gt_masked_lpips"]
    b=d[d["method"]==f"target_s{BASE}"].set_index("idx")["gt_masked_lpips"]
    j=a.index.intersection(b.index)
    return (a.loc[j]-b.loc[j]).values

def boot_ci(x, nboot=NBOOT, seed=SEED):
    rng=np.random.default_rng(seed); n=len(x)
    if n==0: return (np.nan,np.nan,np.nan)
    bs=[rng.choice(x,n,replace=True).mean() for _ in range(nboot)]
    return x.mean(), np.percentile(bs,2.5), np.percentile(bs,97.5)

def main():
    ap=argparse.ArgumentParser(); ap.add_argument("--data",default="."); a=ap.parse_args()
    df=load(a.data)
    runs=[r for r in HARD if r in df["run"].unique()]
    if not runs:
        runs=sorted([r for r in df["run"].unique() if "large" in r or "object" in r or "inst" in r])
    print("hard workloads:", runs)

    for fam in ("Times New Roman","Nimbus Roman","DejaVu Serif"):
        if any(fam==f.name for f in font_manager.fontManager.ttflist):
            plt.rcParams["font.family"]="serif"; plt.rcParams["font.serif"]=[fam]; break
    fig,(ax1,ax2)=plt.subplots(1,2,figsize=(10,3.6))
    stats={}
    for run in runs:
        means=[]; los=[]; his=[]; exc=[]
        for s in STEPS:
            d=paired_delta(df,run,s)
            m,lo,hi=boot_ci(d); means.append(m); los.append(lo); his.append(hi)
            exc.append(float((d>0.02).mean()) if len(d) else np.nan)
            stats[(run,s)]=(m, d.std() if len(d) else np.nan, exc[-1], len(d))
        ax1.errorbar(STEPS, means, yerr=[np.array(means)-np.array(los),
                     np.array(his)-np.array(means)], marker="o", capsize=2, label=run)
        ax2.plot(STEPS, exc, marker="s", label=run)
    ax1.axhline(0.02, color="grey", ls=":", lw=1); ax1.axhline(0,color="k",lw=0.5)
    ax1.set_xlabel("target steps $s$"); ax1.set_ylabel(r"paired $\Delta(s)=$GT-m$(s)-$GT-m$(s24)$")
    ax1.set_title("Boundary map (paired degradation)"); ax1.invert_xaxis(); ax1.grid(ls=":",alpha=0.5)
    ax2.set_xlabel("target steps $s$"); ax2.set_ylabel(r"$P(\Delta>0.02)$")
    ax2.set_title("Exceedance"); ax2.invert_xaxis(); ax2.grid(ls=":",alpha=0.5)
    ax2.legend(fontsize=7)
    fig.tight_layout(); fig.savefig("fig_f3_boundary.pdf",bbox_inches="tight")
    fig.savefig("fig_f3_boundary.png",dpi=150,bbox_inches="tight")

    # boundary table
    with open("table_t_boundary.tex","w") as f:
        f.write("% auto-generated by make_f3_boundary.py\n\\begin{table}[t]\\centering\\small\n")
        f.write("\\setlength{\\tabcolsep}{4pt}\n")
        f.write("\\caption{Boundary map: paired $\\Delta(s)$ mean, sd, and $P(\\Delta{>}0.02)$ per hard workload.}\n")
        f.write("\\label{tab:boundary}\n\\begin{tabular}{@{}l"+ "c"*len(STEPS) +"@{}}\n\\toprule\n")
        f.write("Workload & "+" & ".join(f"s{s}" for s in STEPS)+" \\\\\n\\midrule\n")
        for run in runs:
            cells=[f"{stats[(run,s)][0]:+.3f} ({stats[(run,s)][2]*100:.0f}\\%)" for s in STEPS]
            f.write(f"{run} & "+" & ".join(cells)+" \\\\\n")
        f.write("\\bottomrule\n\\end{tabular}\n"
                "\\\\[2pt]{\\footnotesize Each cell: mean $\\Delta$ (exceedance $P(\\Delta{>}0.02)$).}\n\\end{table}\n")

    # non-monotonicity check s20 vs s16 on large masks
    with open("table_t_nonmono.tex","w") as f:
        f.write("% s20 vs s16 non-monotonicity (large masks)\n\\begin{table}[t]\\centering\\small\n")
        f.write("\\caption{Non-monotonicity: $\\Delta(s20)-\\Delta(s16)$ on large masks (positive = s20 worse).}\n")
        f.write("\\label{tab:nonmono}\n\\begin{tabular}{@{}lc@{}}\n\\toprule\nWorkload & $\\Delta(s20){-}\\Delta(s16)$ \\\\\n\\midrule\n")
        for run in runs:
            if "large" in run:
                diff=stats[(run,20)][0]-stats[(run,16)][0]
                f.write(f"{run} & {diff:+.3f} \\\\\n")
        f.write("\\bottomrule\n\\end{tabular}\n\\end{table}\n")
    print("wrote fig_f3_boundary.pdf/.png, table_t_boundary.tex, table_t_nonmono.tex")
    print("\n[cross-check vs locked numbers]")
    for run in runs:
        print(f"  {run}: "+", ".join(f"s{s} P>.02={stats[(run,s)][2]*100:.0f}%" for s in STEPS))

if __name__=="__main__":
    main()
